### ISSUE TITLE
Should not show passwords while typing

### ISSUE THREAD

**Issue by felipesabino** [davglass/git-travis#5]
It currently shows the password while it's been typed, but it should be hidden for security reasons. 

![screenshot 2015-01-27 09 21 19](https://cloud.githubusercontent.com/assets/700480/5931540/edfdb3da-a653-11e4-9a06-0cf83351a9c6.png)

I believe this happens in this line [/lib/index.js#L252](https://github.com/davglass/git-travis/blob/70fe569647f9b031ca2c63ccceec4152640b4333/lib/index.js#L252)

**Comment by davglass** [comment]
Fix pushed in `git-travis@1.0.0`.
